name: Docker-Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_IMAGE }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE }}:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_IMAGE }}:latest

      - name: Remove old container (ignore error if not exist)
        run: sudo docker rm -f myapp-container || true

      - name: Run Docker container
        run: sudo docker run -d -p 3000:3000 --name myapp-container ${{ secrets.DOCKER_IMAGE }}:latest
